### ISSUE TITLE
error with keyring on debian wheezy

### ISSUE THREAD

**Issue by stefaca** [vintitres/gnome-shell-google-calendar#10]
I have installed all of dependency but when I start instalation of extension this is error: 

Traceback (most recent call last):
  File "./gnome-shell-google-calendar.py", line 444, in <module>
    email, password = keyring.get_credentials()
  File "/home/stefaca/PRGs/gnome-shell/gnome-shell-google-calendar/keyring.py", line 34, in get_credentials
    item_id = get_item_id()
  File "/home/stefaca/PRGs/gnome-shell/gnome-shell-google-calendar/keyring.py", line 29, in get_item_id
    _display_name, _attrs, '', True)
gnomekeyring.NoSuchKeyringError

On my system I'm using unsafe keyring; can be told that I don't have keyring at all

**Comment by vintitres** [comment]
It should work now, after daniellawrence's fix.
