### ISSUE TITLE
Redirection error

### ISSUE THREAD

**Issue by seajulien** [vintitres/gnome-shell-google-calendar#21]
Hi, 

I tried your program, but I get an error...
I can log, but I get the following return and nothing appears on the calendar

---

julien@MYCOMPUTER:~/gnome-shell-google-calendar$ ./gnome-shell-google-calendar.py 
Logging in as 'MYEMAIL@gmail.com'...
Traceback (most recent call last):
  File "./gnome-shell-google-calendar.py", line 457, in <module>
    myserver = CalendarServer(client)
  File "./gnome-shell-google-calendar.py", line 197, in **init**
    self.calendars = self.get_calendars()
  File "./gnome-shell-google-calendar.py", line 246, in get_calendars
    feed = self.client.GetAllCalendarsFeed()
  File "/usr/lib/pymodules/python2.7/gdata/calendar/client.py", line 177, in get_all_calendars_feed
    *_kwargs)
  File "/usr/lib/pymodules/python2.7/gdata/calendar/client.py", line 124, in get_calendars_feed
    desired_class=desired_class, *_kwargs)
  File "/usr/lib/pymodules/python2.7/gdata/client.py", line 635, in get_feed
    *_kwargs)
  File "/usr/lib/pymodules/python2.7/gdata/client.py", line 299, in request
    *_kwargs)
  File "/usr/lib/pymodules/python2.7/gdata/client.py", line 299, in request
    *_kwargs)
  File "/usr/lib/pymodules/python2.7/gdata/client.py", line 299, in request
    *_kwargs)
  File "/usr/lib/pymodules/python2.7/gdata/client.py", line 299, in request
    **kwargs)
  File "/usr/lib/pymodules/python2.7/gdata/client.py", line 305, in request
    response, RedirectError)
gdata.client.RedirectError: Too many redirects from server: 302, <HTML>
<HEAD>
<TITLE>Moved Temporarily</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">

<H1>Moved Temporarily</H1>

The document has moved <A HREF="https://www.google.com/calendar/feeds/default/allcalendars/full?gsessionid=rcgkNUMqMKY8Yx9Q3DdpHw">here</A>.
</BODY>
## </HTML>

I'm not the only one encountering the issue : http://askubuntu.com/questions/116041/help-with-installing-gnome-shell-google-calendar-extension (see answer at the first comment)

I've no idea on what to do to make it work.

Thanks for your job, nice extension (hope I'll be able to run it)

**Comment by seajulien** [comment]
Ooops, the HTML is interpreted on github :s

It removed the end of the issue, I was saying that at least another people is experiencing : http://askubuntu.com/questions/116041/help-with-installing-gnome-shell-google-calendar-extension

Hope I'll be able to run it, seems good extension

**Comment by vintitres** [comment]
I'm sorry, but I have no idea whats going on there and I have no way of recreating this error. I believe that it's gdata module problem.

**Comment by rkingsbury** [comment]
The script worked beautifully for me for about 2 months on Fedora 17 x64, then I began to get this redirection error. I went into Gnome Online Accounts and toggled Calendar syncing off and back on again, and now it appears to work. Perhaps just a hiccup.

**Comment by paoloantinori** [comment]
I confirm the same error in Fedora 17 and the same fix...

**Comment by jayr0d** [comment]
vintitres, this issue is reproducible by quiting and rerunning the program over and over.  I can get it to happen after a few tries.

**Comment by cloudburst** [comment]
If you get the redirect error, you need to patch your gdata which is broken in Ubuntu currently:
http://code.google.com/p/gdata-python-client/issues/detail?id=268#c18
