### ISSUE TITLE
update failed after enabling 2-step verification

### ISSUE THREAD

**Issue by kitingChris** [vintitres/gnome-shell-google-calendar#27]
After enabling [2-step verification](https://support.google.com/accounts/bin/answer.py?hl=en&topic=1056283&answer=180744&rd=1) and granting gnome shell new access i can no longer update my calenders.

```
$ sh -c "python /opt/gnome-shell-google-calendar/gnome-shell-google-calendar.py --account=ACCOUNT_EMAIL"
Logging in as 'ACCOUNT_EMAIL...
Traceback (most recent call last):
  File "/opt/gnome-shell-google-calendar/gnome-shell-google-calendar.py", line 462, in <module>
    myserver = CalendarServer(client)
  File "/opt/gnome-shell-google-calendar/gnome-shell-google-calendar.py", line 198, in __init__
    self.calendars = self.get_calendars()
  File "/opt/gnome-shell-google-calendar/gnome-shell-google-calendar.py", line 247, in get_calendars
    feed = self.client.GetAllCalendarsFeed()
  File "/usr/lib/pymodules/python2.7/gdata/calendar/client.py", line 177, in get_all_calendars_feed
    **kwargs)
  File "/usr/lib/pymodules/python2.7/gdata/calendar/client.py", line 124, in get_calendars_feed
    desired_class=desired_class, **kwargs)
  File "/usr/lib/pymodules/python2.7/gdata/client.py", line 635, in get_feed
    **kwargs)
  File "/usr/lib/pymodules/python2.7/gdata/client.py", line 299, in request
    **kwargs)
  File "/usr/lib/pymodules/python2.7/gdata/client.py", line 299, in request
    **kwargs)
  File "/usr/lib/pymodules/python2.7/gdata/client.py", line 299, in request
    **kwargs)
  File "/usr/lib/pymodules/python2.7/gdata/client.py", line 299, in request
    **kwargs)
  File "/usr/lib/pymodules/python2.7/gdata/client.py", line 305, in request
    response, RedirectError)
gdata.client.RedirectError: Too many redirects from server: 302, <HTML>
<HEAD>
<TITLE>Moved Temporarily</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Moved Temporarily</H1>
The document has moved <A HREF="https://www.google.com/calendar/feeds/default/allcalendars/full?gsessionid=XXXXXXXXXXXXXXXXX">here</A>.
</BODY>
</HTML>
```

**Comment by kitingChris** [comment]
seems to work again ... _confused_

**Comment by jayr0d** [comment]
Duplicate of issue #21.
